// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: media.sql

package db

import (
	"context"
	"database/sql"
)

const createMedia = `-- name: CreateMedia :one
INSERT INTO media (
    filename, stored_name, url, type, mime_type, size, user_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, filename, stored_name, url, type, mime_type, size, user_id, created_at, updated_at, deleted_at
`

type CreateMediaParams struct {
	Filename   string         `json:"filename"`
	StoredName string         `json:"stored_name"`
	Url        string         `json:"url"`
	Type       sql.NullString `json:"type"`
	MimeType   sql.NullString `json:"mime_type"`
	Size       int64          `json:"size"`
	UserID     int32          `json:"user_id"`
}

func (q *Queries) CreateMedia(ctx context.Context, arg CreateMediaParams) (Medium, error) {
	row := q.db.QueryRowContext(ctx, createMedia,
		arg.Filename,
		arg.StoredName,
		arg.Url,
		arg.Type,
		arg.MimeType,
		arg.Size,
		arg.UserID,
	)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.StoredName,
		&i.Url,
		&i.Type,
		&i.MimeType,
		&i.Size,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getMediaByID = `-- name: GetMediaByID :one
SELECT id, filename, stored_name, url, type, mime_type, size, user_id, created_at, updated_at, deleted_at FROM media
WHERE id = $1 AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetMediaByID(ctx context.Context, id int32) (Medium, error) {
	row := q.db.QueryRowContext(ctx, getMediaByID, id)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.StoredName,
		&i.Url,
		&i.Type,
		&i.MimeType,
		&i.Size,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listPublicMedia = `-- name: ListPublicMedia :many
SELECT m.id, m.filename, m.stored_name, m.url, m.type, m.mime_type, m.size, m.user_id, m.created_at, m.updated_at, m.deleted_at, u.name as user_name
FROM media m
JOIN users u ON m.user_id = u.id
WHERE m.deleted_at IS NULL
ORDER BY m.created_at DESC
`

type ListPublicMediaRow struct {
	ID         int32          `json:"id"`
	Filename   string         `json:"filename"`
	StoredName string         `json:"stored_name"`
	Url        string         `json:"url"`
	Type       sql.NullString `json:"type"`
	MimeType   sql.NullString `json:"mime_type"`
	Size       int64          `json:"size"`
	UserID     int32          `json:"user_id"`
	CreatedAt  int64          `json:"created_at"`
	UpdatedAt  int64          `json:"updated_at"`
	DeletedAt  sql.NullTime   `json:"deleted_at"`
	UserName   string         `json:"user_name"`
}

func (q *Queries) ListPublicMedia(ctx context.Context) ([]ListPublicMediaRow, error) {
	rows, err := q.db.QueryContext(ctx, listPublicMedia)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublicMediaRow
	for rows.Next() {
		var i ListPublicMediaRow
		if err := rows.Scan(
			&i.ID,
			&i.Filename,
			&i.StoredName,
			&i.Url,
			&i.Type,
			&i.MimeType,
			&i.Size,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserMedia = `-- name: ListUserMedia :many
SELECT id, filename, stored_name, url, type, mime_type, size, user_id, created_at, updated_at, deleted_at FROM media
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListUserMedia(ctx context.Context, userID int32) ([]Medium, error) {
	rows, err := q.db.QueryContext(ctx, listUserMedia, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Medium
	for rows.Next() {
		var i Medium
		if err := rows.Scan(
			&i.ID,
			&i.Filename,
			&i.StoredName,
			&i.Url,
			&i.Type,
			&i.MimeType,
			&i.Size,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteMedia = `-- name: SoftDeleteMedia :exec
UPDATE media
SET deleted_at = NOW()
WHERE id = $1
`

func (q *Queries) SoftDeleteMedia(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, softDeleteMedia, id)
	return err
}

const updateMedia = `-- name: UpdateMedia :one
UPDATE media
SET 
    filename = $2,
    type = $3,
    mime_type = $4,
    size = $5,
    updated_at = (EXTRACT(EPOCH FROM NOW()) * 1000)
WHERE id = $1
RETURNING id, filename, stored_name, url, type, mime_type, size, user_id, created_at, updated_at, deleted_at
`

type UpdateMediaParams struct {
	ID       int32          `json:"id"`
	Filename string         `json:"filename"`
	Type     sql.NullString `json:"type"`
	MimeType sql.NullString `json:"mime_type"`
	Size     int64          `json:"size"`
}

func (q *Queries) UpdateMedia(ctx context.Context, arg UpdateMediaParams) (Medium, error) {
	row := q.db.QueryRowContext(ctx, updateMedia,
		arg.ID,
		arg.Filename,
		arg.Type,
		arg.MimeType,
		arg.Size,
	)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.StoredName,
		&i.Url,
		&i.Type,
		&i.MimeType,
		&i.Size,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
