// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: media.sql

package db

import (
	"context"
	"database/sql"
)

const countPublicMedia = `-- name: CountPublicMedia :one
SELECT COUNT(*) FROM media
WHERE deleted_at IS NULL
`

func (q *Queries) CountPublicMedia(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPublicMedia)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMedia = `-- name: CreateMedia :one
INSERT INTO media (
    filename, stored_name, url, type, mime_type, size, user_id,
    created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    (EXTRACT(EPOCH FROM NOW()) * 1000)::BIGINT,
    (EXTRACT(EPOCH FROM NOW()) * 1000)::BIGINT
)
RETURNING
    id, filename, stored_name, url,
    COALESCE(type, '') as type,
    COALESCE(mime_type, '') as mime_type,
    size, user_id,
    COALESCE(created_at, 0)::BIGINT as created_at,
    COALESCE(updated_at, 0)::BIGINT as updated_at,
    deleted_at
`

type CreateMediaParams struct {
	Filename   string         `json:"filename"`
	StoredName string         `json:"stored_name"`
	Url        string         `json:"url"`
	Type       sql.NullString `json:"type"`
	MimeType   sql.NullString `json:"mime_type"`
	Size       int64          `json:"size"`
	UserID     int64          `json:"user_id"`
}

type CreateMediaRow struct {
	ID         int64        `json:"id"`
	Filename   string       `json:"filename"`
	StoredName string       `json:"stored_name"`
	Url        string       `json:"url"`
	Type       string       `json:"type"`
	MimeType   string       `json:"mime_type"`
	Size       int64        `json:"size"`
	UserID     int64        `json:"user_id"`
	CreatedAt  int64        `json:"created_at"`
	UpdatedAt  int64        `json:"updated_at"`
	DeletedAt  sql.NullTime `json:"deleted_at"`
}

func (q *Queries) CreateMedia(ctx context.Context, arg CreateMediaParams) (CreateMediaRow, error) {
	row := q.db.QueryRowContext(ctx, createMedia,
		arg.Filename,
		arg.StoredName,
		arg.Url,
		arg.Type,
		arg.MimeType,
		arg.Size,
		arg.UserID,
	)
	var i CreateMediaRow
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.StoredName,
		&i.Url,
		&i.Type,
		&i.MimeType,
		&i.Size,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getMediaByID = `-- name: GetMediaByID :one
SELECT
    id, filename, stored_name, url,
    COALESCE(type, '') as type,
    COALESCE(mime_type, '') as mime_type,
    size, user_id,
    COALESCE(created_at, 0)::BIGINT as created_at,
    COALESCE(updated_at, 0)::BIGINT as updated_at,
    deleted_at
FROM media
WHERE id = $1 AND deleted_at IS NULL
LIMIT 1
`

type GetMediaByIDRow struct {
	ID         int64        `json:"id"`
	Filename   string       `json:"filename"`
	StoredName string       `json:"stored_name"`
	Url        string       `json:"url"`
	Type       string       `json:"type"`
	MimeType   string       `json:"mime_type"`
	Size       int64        `json:"size"`
	UserID     int64        `json:"user_id"`
	CreatedAt  int64        `json:"created_at"`
	UpdatedAt  int64        `json:"updated_at"`
	DeletedAt  sql.NullTime `json:"deleted_at"`
}

func (q *Queries) GetMediaByID(ctx context.Context, id int64) (GetMediaByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getMediaByID, id)
	var i GetMediaByIDRow
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.StoredName,
		&i.Url,
		&i.Type,
		&i.MimeType,
		&i.Size,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listPublicMedia = `-- name: ListPublicMedia :many
SELECT
    m.id, m.filename, m.stored_name, m.url,
    COALESCE(m.type, '') as type,
    COALESCE(m.mime_type, '') as mime_type,
    m.size, m.user_id,
    COALESCE(m.created_at, 0)::BIGINT as created_at,
    COALESCE(m.updated_at, 0)::BIGINT as updated_at,
    m.deleted_at,
    u.name as user_name,
    u.tel as user_tel,
    u.email as user_email
FROM media m
JOIN users u ON m.user_id = u.id
WHERE m.deleted_at IS NULL
ORDER BY m.created_at DESC
LIMIT $1 OFFSET $2
`

type ListPublicMediaParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListPublicMediaRow struct {
	ID         int64          `json:"id"`
	Filename   string         `json:"filename"`
	StoredName string         `json:"stored_name"`
	Url        string         `json:"url"`
	Type       string         `json:"type"`
	MimeType   string         `json:"mime_type"`
	Size       int64          `json:"size"`
	UserID     int64          `json:"user_id"`
	CreatedAt  int64          `json:"created_at"`
	UpdatedAt  int64          `json:"updated_at"`
	DeletedAt  sql.NullTime   `json:"deleted_at"`
	UserName   string         `json:"user_name"`
	UserTel    sql.NullString `json:"user_tel"`
	UserEmail  string         `json:"user_email"`
}

func (q *Queries) ListPublicMedia(ctx context.Context, arg ListPublicMediaParams) ([]ListPublicMediaRow, error) {
	rows, err := q.db.QueryContext(ctx, listPublicMedia, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublicMediaRow
	for rows.Next() {
		var i ListPublicMediaRow
		if err := rows.Scan(
			&i.ID,
			&i.Filename,
			&i.StoredName,
			&i.Url,
			&i.Type,
			&i.MimeType,
			&i.Size,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.UserName,
			&i.UserTel,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserMedia = `-- name: ListUserMedia :many
SELECT
    id, filename, stored_name, url,
    COALESCE(type, '') as type,
    COALESCE(mime_type, '') as mime_type,
    size, user_id,
    COALESCE(created_at, 0)::BIGINT as created_at,
    COALESCE(updated_at, 0)::BIGINT as updated_at,
    deleted_at
FROM media
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

type ListUserMediaRow struct {
	ID         int64        `json:"id"`
	Filename   string       `json:"filename"`
	StoredName string       `json:"stored_name"`
	Url        string       `json:"url"`
	Type       string       `json:"type"`
	MimeType   string       `json:"mime_type"`
	Size       int64        `json:"size"`
	UserID     int64        `json:"user_id"`
	UserEmail  string       `json:"user_email"` // Add this field
	CreatedAt  int64        `json:"created_at"`
	UpdatedAt  int64        `json:"updated_at"`
	DeletedAt  sql.NullTime `json:"deleted_at"`
}

func (q *Queries) ListUserMedia(ctx context.Context, userID int64) ([]ListUserMediaRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserMedia, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserMediaRow
	for rows.Next() {
		var i ListUserMediaRow
		if err := rows.Scan(
			&i.ID,
			&i.Filename,
			&i.StoredName,
			&i.Url,
			&i.Type,
			&i.MimeType,
			&i.Size,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const permanentlyDeleteMedia = `-- name: PermanentlyDeleteMedia :exec
DELETE FROM media
WHERE id = $1
`

func (q *Queries) PermanentlyDeleteMedia(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, permanentlyDeleteMedia, id)
	return err
}

const softDeleteMedia = `-- name: SoftDeleteMedia :exec
UPDATE media
SET deleted_at = NOW()
WHERE id = $1
`

func (q *Queries) SoftDeleteMedia(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, softDeleteMedia, id)
	return err
}

const updateMedia = `-- name: UpdateMedia :one
UPDATE media
SET
    filename = $2,
    type = $3,
    mime_type = $4,
    size = $5,
    updated_at = (EXTRACT(EPOCH FROM NOW()) * 1000)::BIGINT
WHERE id = $1
RETURNING
    id, filename, stored_name, url,
    COALESCE(type, '') as type,
    COALESCE(mime_type, '') as mime_type,
    size, user_id,
    COALESCE(created_at, 0)::BIGINT as created_at,
    COALESCE(updated_at, 0)::BIGINT as updated_at,
    deleted_at
`

type UpdateMediaParams struct {
	ID       int64          `json:"id"`
	Filename string         `json:"filename"`
	Type     sql.NullString `json:"type"`
	MimeType sql.NullString `json:"mime_type"`
	Size     int64          `json:"size"`
}

type UpdateMediaRow struct {
	ID         int64        `json:"id"`
	Filename   string       `json:"filename"`
	StoredName string       `json:"stored_name"`
	Url        string       `json:"url"`
	Type       string       `json:"type"`
	MimeType   string       `json:"mime_type"`
	Size       int64        `json:"size"`
	UserID     int64        `json:"user_id"`
	CreatedAt  int64        `json:"created_at"`
	UpdatedAt  int64        `json:"updated_at"`
	DeletedAt  sql.NullTime `json:"deleted_at"`
}

func (q *Queries) UpdateMedia(ctx context.Context, arg UpdateMediaParams) (UpdateMediaRow, error) {
	row := q.db.QueryRowContext(ctx, updateMedia,
		arg.ID,
		arg.Filename,
		arg.Type,
		arg.MimeType,
		arg.Size,
	)
	var i UpdateMediaRow
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.StoredName,
		&i.Url,
		&i.Type,
		&i.MimeType,
		&i.Size,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
