// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Album struct {
	ID          int64          `json:"id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	UserID      int64          `json:"user_id"`
	IsPublic    sql.NullBool   `json:"is_public"`
	IsShared    sql.NullBool   `json:"is_shared"`
	CreatedAt   int64          `json:"created_at"`
	UpdatedAt   int64          `json:"updated_at"`
	DeletedAt   sql.NullTime   `json:"deleted_at"`
}

type AlbumMedium struct {
	AlbumID int64 `json:"album_id"`
	MediaID int64 `json:"media_id"`
}

type Medium struct {
	ID         int64          `json:"id"`
	Filename   string         `json:"filename"`
	StoredName string         `json:"stored_name"`
	Url        string         `json:"url"`
	Type       sql.NullString `json:"type"`
	MimeType   sql.NullString `json:"mime_type"`
	Size       int64          `json:"size"`
	UserID     int64          `json:"user_id"`
	CreatedAt  int64          `json:"created_at"`
	UpdatedAt  int64          `json:"updated_at"`
	DeletedAt  sql.NullTime   `json:"deleted_at"`
}

type Role struct {
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

type User struct {
	ID            int64          `json:"id"`
	Email         string         `json:"email"`
	Password      string         `json:"password"`
	Name          string         `json:"name"`
	Tel           sql.NullString `json:"tel"`
	Age           sql.NullInt64  `json:"age"`
	Address       sql.NullString `json:"address"`
	City          sql.NullString `json:"city"`
	Country       sql.NullString `json:"country"`
	Gender        sql.NullString `json:"gender"`
	EmailVerified sql.NullBool   `json:"email_verified"`
	CreatedAt     int64          `json:"created_at"`
	UpdatedAt     int64          `json:"updated_at"`
	DeletedAt     sql.NullTime   `json:"deleted_at"`
}

type UserRole struct {
	UserID int64 `json:"user_id"`
	RoleID int64 `json:"role_id"`
}

type Video struct {
	ID           int64          `json:"id"`
	VideoID      string         `json:"video_id"`
	Title        string         `json:"title"`
	Description  sql.NullString `json:"description"`
	PublishedAt  sql.NullTime   `json:"published_at"`
	Views        sql.NullInt64  `json:"views"`
	Likes        sql.NullInt64  `json:"likes"`
	ThumbnailUrl sql.NullString `json:"thumbnail_url"`
	CreatedAt    int64          `json:"created_at"`
	UpdatedAt    int64          `json:"updated_at"`
	DeletedAt    sql.NullTime   `json:"deleted_at"`
}
