// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: muvi.sql

package db

import (
	"context"
	"database/sql"
)

const countMuvi = `-- name: CountMuvi :one
SELECT COUNT(*) FROM muvi
`

func (q *Queries) CountMuvi(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMuvi)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteMuvi = `-- name: DeleteMuvi :exec
DELETE FROM muvi WHERE id = $1
`

func (q *Queries) DeleteMuvi(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteMuvi, id)
	return err
}

const getMuviByID = `-- name: GetMuviByID :one
SELECT id, name, description, created_at, updated_at, deleted_at FROM muvi WHERE id = $1
`

func (q *Queries) GetMuviByID(ctx context.Context, id int32) (Muvi, error) {
	row := q.db.QueryRowContext(ctx, getMuviByID, id)
	var i Muvi
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listMuvi = `-- name: ListMuvi :many
SELECT id, name, description, created_at, updated_at, deleted_at FROM muvi
`

func (q *Queries) ListMuvi(ctx context.Context) ([]Muvi, error) {
	rows, err := q.db.QueryContext(ctx, listMuvi)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Muvi
	for rows.Next() {
		var i Muvi
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMuvi = `-- name: UpdateMuvi :exec
UPDATE muvi SET name = $2, description = $3 WHERE id = $1
`

type UpdateMuviParams struct {
	ID          int32          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) UpdateMuvi(ctx context.Context, arg UpdateMuviParams) error {
	_, err := q.db.ExecContext(ctx, updateMuvi, arg.ID, arg.Name, arg.Description)
	return err
}
