// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: videos.sql

package db

import (
	"context"
	"database/sql"
)

const createVideo = `-- name: CreateVideo :one
INSERT INTO videos (
    video_id, title, description, published_at, views, likes, thumbnail_url,
    created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    (EXTRACT(EPOCH FROM NOW()) * 1000)::BIGINT,
    (EXTRACT(EPOCH FROM NOW()) * 1000)::BIGINT
)
ON CONFLICT (video_id) DO UPDATE SET
    title = EXCLUDED.title,
    description = EXCLUDED.description,
    views = EXCLUDED.views,
    likes = EXCLUDED.likes,
    thumbnail_url = EXCLUDED.thumbnail_url,
    updated_at = (EXTRACT(EPOCH FROM NOW()) * 1000)::BIGINT
RETURNING id, video_id, title, description, published_at, views, likes, thumbnail_url, created_at, updated_at, deleted_at
`

type CreateVideoParams struct {
	VideoID      string         `json:"video_id"`
	Title        string         `json:"title"`
	Description  sql.NullString `json:"description"`
	PublishedAt  sql.NullTime   `json:"published_at"`
	Views        sql.NullInt64  `json:"views"`
	Likes        sql.NullInt64  `json:"likes"`
	ThumbnailUrl sql.NullString `json:"thumbnail_url"`
}

func (q *Queries) CreateVideo(ctx context.Context, arg CreateVideoParams) (Video, error) {
	row := q.db.QueryRowContext(ctx, createVideo,
		arg.VideoID,
		arg.Title,
		arg.Description,
		arg.PublishedAt,
		arg.Views,
		arg.Likes,
		arg.ThumbnailUrl,
	)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.Title,
		&i.Description,
		&i.PublishedAt,
		&i.Views,
		&i.Likes,
		&i.ThumbnailUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getVideoByID = `-- name: GetVideoByID :one
SELECT id, video_id, title, description, published_at, views, likes, thumbnail_url, created_at, updated_at, deleted_at FROM videos
WHERE id = $1 AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetVideoByID(ctx context.Context, id int64) (Video, error) {
	row := q.db.QueryRowContext(ctx, getVideoByID, id)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.Title,
		&i.Description,
		&i.PublishedAt,
		&i.Views,
		&i.Likes,
		&i.ThumbnailUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listVideos = `-- name: ListVideos :many
SELECT id, video_id, title, description, published_at, views, likes, thumbnail_url, created_at, updated_at, deleted_at FROM videos
WHERE deleted_at IS NULL
ORDER BY published_at DESC
LIMIT $1 OFFSET $2
`

type ListVideosParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListVideos(ctx context.Context, arg ListVideosParams) ([]Video, error) {
	rows, err := q.db.QueryContext(ctx, listVideos, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Video
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.VideoID,
			&i.Title,
			&i.Description,
			&i.PublishedAt,
			&i.Views,
			&i.Likes,
			&i.ThumbnailUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteVideo = `-- name: SoftDeleteVideo :exec
UPDATE videos
SET deleted_at = NOW()
WHERE id = $1
`

func (q *Queries) SoftDeleteVideo(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, softDeleteVideo, id)
	return err
}
